### ISSUE TITLE
getStateFromMeta is deprecated

### ISSUE THREAD

**Issue by Gamewalker** [McJty/ModTutorials#10]
Hey,

in 1.10 the method getStateFromMeta is deprecated, whats the proper way to handle the facing now?

Another question, is there an easy way to spawn a predefined structure into the world?

Thanks for your awesome tutorial stuff, it helped me so much.

**Comment by McJty** [comment]
You still have to implement getStateFromMeta(). It is only deprecated for calling it manually. Not for overriding it.

What kind of predefined structure?

**Comment by Gamewalker** [comment]
ok, so I will suppress the IntelliJ warning. 

I have a structure like this: http://i65.tinypic.com/2v9f3uf.png (Pokestop in the background)
I just created a template with ruins mod to spawn it into the world but I don't want to rely on another mod. Is there another way besides getting a random xyz and place each block from there?

**Comment by McJty** [comment]
No idea how the ruins mod works to be honest. Perhaps check out the format it has?

**Comment by Gamewalker** [comment]
I dont want to use the ruins mod, I want to implement it without any other mods. But I dont think there is an easy way to spawn predefined structures into the game.
