### ISSUE TITLE
[expired] website gone

### ISSUE THREAD

**Issue by kreezxil** [McJty/ModTutorials#17]
![image](https://user-images.githubusercontent.com/3880072/27761632-aa147fc8-5e25-11e7-8a8f-8bf549eb2b91.png)

**Comment by McJty** [comment]
The website has moved to mcjty.eu a long time ago and that was announced at many places

**Comment by kreezxil** [comment]
they didn't update it on MMD discord pinned messages. in #development, i'll let em know.

**Comment by Shadows-of-Fire** [comment]
Its not updated in the topic or the readme here, might wanna change those too.
