### ISSUE TITLE
Use localization instead of raw strings

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [McJty/ModTutorials#23]
I believe that good education is key to a healthy modding community. Seeing as your tutorials cover quite a few topics and are rather popular, I believe it is especially necessary that your tutorials promote good patterns.

DataBlock [(1)](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/blocks/datablock/DataBlock.java#L97), PacketSendKey.Handler [(1)](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/network/PacketSendKey.java#L55) and TeleportCommand [(1)](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/commands/TeleportCommand.java#L55) [(2)](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/commands/TeleportCommand.java#L36) suffer from lack of localization in strings that are displayed to the user. Using raw strings makes it pretty much impossible to translate the mod to other languages, so this should really be avoided.

You have to use TextComponentTranslation. TeleportCommand has to be made more similar to this https://gist.github.com/JamiesWhiteShirt/52775b5ccc96847dd36058de446369af.

**Comment by McJty** [comment]
The problem with DataBlock is a bit more complicated as The One Probe works server side and no localization can be done there. This will require an api change in The One Probe

**Comment by McJty** [comment]
Handler is just debug info and also server-side. Same problem

**Comment by McJty** [comment]
TeleportCommand I cannot fix. For (1) that's an error and I don't think I'll bother translating those. In a regular mod there are literally too many of those and in practice they should not occur under normal usage.

For (2) I cannot localize that as that's the actual syntax for using the command.

**Comment by McJty** [comment]
Actually I forgot that I did implement support in TOP for this so that one I can fix at least

**Comment by McJty** [comment]
Question, how can I add a space after this in my lang file?

message.modtut.counter=Counter:

**Comment by JamiesWhiteShirt** [comment]
DataBlock:
How TOP works does not matter here. The problem is in `onBlockActivated` which is using `TextComponentString` instead of `TextComponentTranslation`.

In case you are not aware, TextComponentTranslation is localized on the client. You can use it on the server. In fact, that is what you should always use on the server.

**Comment by JamiesWhiteShirt** [comment]
PacketSendKey.Handler:
I get that it is only debug info, but the problem is that it might give the reader an impression that they can use this pattern everywhere. They should not.

Again, you can safely use TextComponentTranslation here.

**Comment by McJty** [comment]
Ah I thought you were refering to the TOP tooltip. I missed the other occurance

**Comment by McJty** [comment]
Question:
                player.sendStatusMessage(new TextComponentString(TextFormatting.GREEN + "Counter: " + counter), false);

How do I specify the color green with a translationKey?

**Comment by JamiesWhiteShirt** [comment]
TeleportCommand:
(1) again, even if it's debug info, it should go the extra mile to ensure people use localisation.
(2) The return value of getUsage is a lang key. It just happens to work because there is no entry with that name.

**Comment by McJty** [comment]
For debug info I don't agree. Debug info is mostly for me and I don't want to bother with translated messages. Especially not because they may occur in a log file that a player sends to me and I want to be able to read that. In fact for this reason alone I strongly think that it is a very bad idea to translate debug messages like those.

**Comment by JamiesWhiteShirt** [comment]
To style TextComponentTranslation you have to set the style on the text component object. This is how the help command does it.

```java
TextComponentTranslation textcomponenttranslation1 = new TextComponentTranslation("commands.help.header", new Object[] {Integer.valueOf(k + 1), Integer.valueOf(j + 1)});
textcomponenttranslation1.getStyle().setColor(TextFormatting.DARK_GREEN);
```

**Comment by McJty** [comment]
And how would I include the argument in the lang file? I have no experience with this and I have no clue how to specify that parameter (i.e. the counter value in DataBlock)

**Comment by JamiesWhiteShirt** [comment]
If you will not use TextComponentTranslation for debug messages, at least make it clear that the messages ARE debug messages and that you should use TextComponentTranslation for production. It does not come off that way.

**Comment by JamiesWhiteShirt** [comment]
I see you figured out the formatting in the lang file. You can use `%d` instead of `%s` to avoid having to turn the integer to a string manually.

**Comment by McJty** [comment]
ok thanks

**Comment by McJty** [comment]
One final thing about the debug messages and exceptions in general. Even in production (final released mod) these kinds of exceptions should not be translated IMHO. I shudder at the idea that players would give me logs where I cannot even read my own generated exceptions
