### ISSUE TITLE
PedestalTESR does not listen for resource reload

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [McJty/ModTutorials#24]
I believe that good education is key to a healthy modding community. Seeing as your tutorials cover quite a few topics and are rather popular, I believe it is especially necessary that your tutorials promote good patterns.

PedestalTESR is not listening for resource reloads. This means the cached baked model will not change when resources are reloaded. Look for usages of `IResourceManagerReloadListener` in the vanilla codebase and you will see what I mean.

**Comment by McJty** [comment]
Hmm that is not clear. Can you elaborate exactly how I should fix that? Never bothered with that resource reload thing really

**Comment by McJty** [comment]
I merged your changes and updated the tutorial. Thanks. This way I do learn a bit myself :-)
