### ISSUE TITLE
Suggestion: Use capability.cast(instance) instead of unsafe cast

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [McJty/ModTutorials#25]
I believe that good education is key to a healthy modding community. Seeing as your tutorials cover quite a few topics and are rather popular, I believe it is especially necessary that your tutorials promote good patterns.

[TestContainerTileEntity#getCapability is warning about an unsafe cast](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/blocks/testcontainer/TestContainerTileEntity.java#L56). Using `capability.cast(itemStackHandler)` you can avoid the warning. It doesn't really do anything except remove the warning.

**Comment by McJty** [comment]
Done

**Comment by JamiesWhiteShirt** [comment]
You can shorten it a little bit. Seeing as you have already determined that `capability` is equal to `CapabilityItemHandler.ITEM_HANDLER_CAPABILITY` you can use `capability`.

**Comment by McJty** [comment]
I tried that but that doesn't work:

    @Override
    public <T> T getCapability(Capability<T> capability, EnumFacing facing) {
        if (capability == CapabilityItemHandler.ITEM_HANDLER_CAPABILITY) {
            return capability.cast(itemStackHandler);
        }
        return super.getCapability(capability, facing);
    }
}


Results in:

Error:(56, 30) java: method cast in class net.minecraftforge.common.capabilities.Capability<T> cannot be applied to given types;
  required: T
  found: net.minecraftforge.items.ItemStackHandler
  reason: cannot infer type-variable(s) R
    (argument mismatch; net.minecraftforge.items.ItemStackHandler cannot be converted to T)

**Comment by JamiesWhiteShirt** [comment]
Ah, you're right, forgot about that.
