### ISSUE TITLE
Suggestion: Remove re-render trigger for BakedModelBlock

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [McJty/ModTutorials#26]
I believe that good education is key to a healthy modding community. Seeing as your tutorials cover quite a few topics and are rather popular, I believe it is especially necessary that your tutorials promote good patterns.

BakedModelBlock is using `onBlockPlacedBy` to make surrounding blocks re-render. I believe this implementation is flawed and gives people misconceptions about how re-renders should be triggered.

First of all, I think it would be better if BakedModelBlock listens for neighbor updates and then re-renders itself if such an update happens. Anything else might give someone the misconception that they should always trigger this render update when the block is placed for any block that has unlisted properies.

However, even this should be unnecessary, as changing a blockstate re-renders chunks that intersect with the 3x3x3 space that surrounds the block that is set.

I therefore suggest that you should remove the onBlockPlacedBy implementation completely. I believe this will give the exact same result.

**Comment by McJty** [comment]
You are right. I'm pretty sure this was needed at some point (maybe in 1.8 when I started this tutorial). I'll fix it now
