### ISSUE TITLE
PacketSendKey.Handler is vulnerable to arbitrary chunk generation

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [McJty/ModTutorials#27]
I believe that good education is key to a healthy modding community. Seeing as your tutorials cover quite a few topics and are rather popular, I believe it is especially necessary that your tutorials promote good patterns.

[PacketSendKey.Handler](https://github.com/McJty/ModTutorials/blob/1.12/src/main/java/mcjty/modtut/network/PacketSendKey.java) is vulnerable to arbitrary chunk generation. What this means is that a client with malicious intent can overload a server by making it generate arbitrary chunks. The BlockPos sent by the client should be handled with extreme care. You have to verify that the block at the position is loaded using `world.isBlockLoaded(pos)` before accessing the block.

As a side note, the information of a BlockPos can fit in a long. You can therefore do `BlockPos.fromLong(buf.readLong())` and `buf.writeLong(blockPos.toLong())` instead of doing every component.

**Comment by McJty** [comment]
Fixed in code and tutorial. Thanks
