### ISSUE TITLE
Why in common and int Constructor 

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/ModTutorials#4]
For a lots of the blocks you have method a initModel and you call this method in the common proxy, is there reason you do not just call in the block constructor, or is just done to personal preference.

By the good tutorial, one of the best i have seen, has taught, more about modding about than any other I have seen, would love to see more.

**Comment by McJty** [comment]
initModel() is called client side only as the server doesn't care about models. The block constructor however is also called on server side. You can't do any client side code in that
