### ISSUE TITLE
Container Created Twice?

### ISSUE THREAD

**Issue by zenmogwai** [McJty/ModTutorials#9]
Hey, sorry I keep leaving these as issues but I can't find another way to correspond.  I'm learning how to code for Minecraft and I'm trying to understand every method.  So I'm following every line closer than normal.  I noticed that the container is created twice because of the methods in GuiProxy.  Is it supposed to be or is it preferable to create it only once?

Line 19 creates a new TestContainer server side.  Also line 30 creates another new TestContainer client side.   It is possible if I create a TestContainer field in GuiProxy to pass the TestContainer created from the server method down to the client method and then only create one container...

Both approaches (one or two containers) don't appear to cause any errors.  Which is preferable?  Is there a reason why you would want to create one or two containers?

```
12 public class GuiProxy implements IGuiHandler { 
13 
14     @Override 
15     public Object getServerGuiElement(int ID, EntityPlayer player, World world, int x, int y, int z) { 
16         BlockPos pos = new BlockPos(x, y, z); 
17         TileEntity te = world.getTileEntity(pos); 
18         if (te instanceof TestContainerTileEntity) { 
19             return new TestContainer(player.inventory, (TestContainerTileEntity) te); 
20         } 
21         return null; 
22     } 
23 
24     @Override 
25     public Object getClientGuiElement(int ID, EntityPlayer player, World world, int x, int y, int z) { 
26         BlockPos pos = new BlockPos(x, y, z); 
27         TileEntity te = world.getTileEntity(pos); 
28         if (te instanceof TestContainerTileEntity) { 
29             TestContainerTileEntity containerTileEntity = (TestContainerTileEntity) te; 
30             return new TestContainerGui(containerTileEntity, new TestContainer(player.inventory, containerTileEntity)); 
31         } 
32         return null; 
33     } 
```

**Comment by McJty** [comment]
You want two containers because you want your mod to work on servers and on servers you need a container on the server side and one on the client side (different machines usually).
